remove CONFIG_THUMB in config-armv7-a-neon
it will cause following error on android lp5.1
"error: conditional branch to PLT in THUMB-2 not supported yet.
 error: conditional branch to PLT in THUMB-2 not supported yet."

Signed-off-by: gzliu <gzliu@marvell.com>